// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDit69Naa2-yt3NxldhYTfgMwwE77q9JKQ',
    appId: '1:99007200987:web:7de73598dbe54f6c6616fe',
    messagingSenderId: '99007200987',
    projectId: 'holyroad-f21f2',
    authDomain: 'holyroad-f21f2.firebaseapp.com',
    storageBucket: 'holyroad-f21f2.firebasestorage.app',
    measurementId: 'G-7XJZQZGF31',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJ1Rvh3_lgdbvgaLe-Xb7G6vdZ75Lz_SA',
    appId: '1:99007200987:android:0e33fa25dc239c986616fe',
    messagingSenderId: '99007200987',
    projectId: 'holyroad-f21f2',
    storageBucket: 'holyroad-f21f2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDto-bJptxxJxy7ZMeDwaQs00A028otrPU',
    appId: '1:99007200987:ios:be0166a2e8f191416616fe',
    messagingSenderId: '99007200987',
    projectId: 'holyroad-f21f2',
    storageBucket: 'holyroad-f21f2.firebasestorage.app',
    iosClientId: '99007200987-l515bq33g6r9bf6je25eprr4jqhei2su.apps.googleusercontent.com',
    iosBundleId: 'com.holyroad.holyroad',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDto-bJptxxJxy7ZMeDwaQs00A028otrPU',
    appId: '1:99007200987:ios:be0166a2e8f191416616fe',
    messagingSenderId: '99007200987',
    projectId: 'holyroad-f21f2',
    storageBucket: 'holyroad-f21f2.firebasestorage.app',
    iosClientId: '99007200987-l515bq33g6r9bf6je25eprr4jqhei2su.apps.googleusercontent.com',
    iosBundleId: 'com.holyroad.holyroad',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDit69Naa2-yt3NxldhYTfgMwwE77q9JKQ',
    appId: '1:99007200987:web:3f1499164f260da36616fe',
    messagingSenderId: '99007200987',
    projectId: 'holyroad-f21f2',
    authDomain: 'holyroad-f21f2.firebaseapp.com',
    storageBucket: 'holyroad-f21f2.firebasestorage.app',
    measurementId: 'G-MG5FC3Z2E5',
  );

}